// Code generated by "stringer -type SortByDir nodes/sort_by_dir.go"; DO NOT EDIT.

package pg_query

import "strconv"

const _SortByDir_name = "SORTBY_DEFAULTSORTBY_ASCSORTBY_DESCSORTBY_USING"

var _SortByDir_index = [...]uint8{0, 14, 24, 35, 47}

func (i SortByDir) String() string {
	if i >= SortByDir(len(_SortByDir_index)-1) {
		return "SortByDir(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SortByDir_name[_SortByDir_index[i]:_SortByDir_index[i+1]]
}
