// Code generated by "stringer -type SortByDir pkg/parser/ast/sort_by_dir.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SORTBY_DEFAULT-0]
	_ = x[SORTBY_ASC-1]
	_ = x[SORTBY_DESC-2]
	_ = x[SORTBY_USING-3]
}

const _SortByDir_name = "SORTBY_DEFAULTSORTBY_ASCSORTBY_DESCSORTBY_USING"

var _SortByDir_index = [...]uint8{0, 14, 24, 35, 47}

func (i SortByDir) String() string {
	if i >= SortByDir(len(_SortByDir_index)-1) {
		return "SortByDir(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SortByDir_name[_SortByDir_index[i]:_SortByDir_index[i+1]]
}
