// Code generated by "stringer -type SQLValueFunctionOp pkg/parser/ast/sql_value_function_op.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SVFOP_CURRENT_DATE-0]
	_ = x[SVFOP_CURRENT_TIME-1]
	_ = x[SVFOP_CURRENT_TIME_N-2]
	_ = x[SVFOP_CURRENT_TIMESTAMP-3]
	_ = x[SVFOP_CURRENT_TIMESTAMP_N-4]
	_ = x[SVFOP_LOCALTIME-5]
	_ = x[SVFOP_LOCALTIME_N-6]
	_ = x[SVFOP_LOCALTIMESTAMP-7]
	_ = x[SVFOP_LOCALTIMESTAMP_N-8]
	_ = x[SVFOP_CURRENT_ROLE-9]
	_ = x[SVFOP_CURRENT_USER-10]
	_ = x[SVFOP_USER-11]
	_ = x[SVFOP_SESSION_USER-12]
	_ = x[SVFOP_CURRENT_CATALOG-13]
	_ = x[SVFOP_CURRENT_SCHEMA-14]
}

const _SQLValueFunctionOp_name = "SVFOP_CURRENT_DATESVFOP_CURRENT_TIMESVFOP_CURRENT_TIME_NSVFOP_CURRENT_TIMESTAMPSVFOP_CURRENT_TIMESTAMP_NSVFOP_LOCALTIMESVFOP_LOCALTIME_NSVFOP_LOCALTIMESTAMPSVFOP_LOCALTIMESTAMP_NSVFOP_CURRENT_ROLESVFOP_CURRENT_USERSVFOP_USERSVFOP_SESSION_USERSVFOP_CURRENT_CATALOGSVFOP_CURRENT_SCHEMA"

var _SQLValueFunctionOp_index = [...]uint16{0, 18, 36, 56, 79, 104, 119, 136, 156, 178, 196, 214, 224, 242, 263, 283}

func (i SQLValueFunctionOp) String() string {
	if i >= SQLValueFunctionOp(len(_SQLValueFunctionOp_index)-1) {
		return "SQLValueFunctionOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SQLValueFunctionOp_name[_SQLValueFunctionOp_index[i]:_SQLValueFunctionOp_index[i+1]]
}
