// Code generated by "stringer -type StmtType nodes/stmt_type.go"; DO NOT EDIT.

package pg_query

import "strconv"

const _StmtType_name = "AckDDLRowsAffectedRowsCopyInUnknown"

var _StmtType_index = [...]uint8{0, 3, 6, 18, 22, 28, 35}

func (i StmtType) String() string {
	if i < 0 || i >= StmtType(len(_StmtType_index)-1) {
		return "StmtType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StmtType_name[_StmtType_index[i]:_StmtType_index[i+1]]
}
