// Code generated by "stringer -type StmtType pkg/parser/ast/stmt_type.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ack-0]
	_ = x[DDL-1]
	_ = x[RowsAffected-2]
	_ = x[Rows-3]
	_ = x[CopyIn-4]
	_ = x[Unknown-5]
}

const _StmtType_name = "AckDDLRowsAffectedRowsCopyInUnknown"

var _StmtType_index = [...]uint8{0, 3, 6, 18, 22, 28, 35}

func (i StmtType) String() string {
	if i < 0 || i >= StmtType(len(_StmtType_index)-1) {
		return "StmtType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StmtType_name[_StmtType_index[i]:_StmtType_index[i+1]]
}
