// Code generated by "stringer -type Context pkg/parser/ast/context.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Context_None-0]
	_ = x[Context_True-1]
	_ = x[Context_False-2]
	_ = x[Context_Select-4]
	_ = x[Context_Update-8]
	_ = x[Context_AConst-16]
	_ = x[Context_FuncCall-32]
	_ = x[Context_TypeName-64]
	_ = x[Context_Operator-128]
}

const (
	_Context_name_0 = "Context_NoneContext_TrueContext_False"
	_Context_name_1 = "Context_Select"
	_Context_name_2 = "Context_Update"
	_Context_name_3 = "Context_AConst"
	_Context_name_4 = "Context_FuncCall"
	_Context_name_5 = "Context_TypeName"
	_Context_name_6 = "Context_Operator"
)

var (
	_Context_index_0 = [...]uint8{0, 12, 24, 37}
)

func (i Context) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _Context_name_0[_Context_index_0[i]:_Context_index_0[i+1]]
	case i == 4:
		return _Context_name_1
	case i == 8:
		return _Context_name_2
	case i == 16:
		return _Context_name_3
	case i == 32:
		return _Context_name_4
	case i == 64:
		return _Context_name_5
	case i == 128:
		return _Context_name_6
	default:
		return "Context(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
