// Code generated by "stringer -type SubLinkType pkg/parser/ast/sub_link_type.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EXISTS_SUBLINK-0]
	_ = x[ALL_SUBLINK-1]
	_ = x[ANY_SUBLINK-2]
	_ = x[ROWCOMPARE_SUBLINK-3]
	_ = x[EXPR_SUBLINK-4]
	_ = x[MULTIEXPR_SUBLINK-5]
	_ = x[ARRAY_SUBLINK-6]
	_ = x[CTE_SUBLINK-7]
}

const _SubLinkType_name = "EXISTS_SUBLINKALL_SUBLINKANY_SUBLINKROWCOMPARE_SUBLINKEXPR_SUBLINKMULTIEXPR_SUBLINKARRAY_SUBLINKCTE_SUBLINK"

var _SubLinkType_index = [...]uint8{0, 14, 25, 36, 54, 66, 83, 96, 107}

func (i SubLinkType) String() string {
	if i >= SubLinkType(len(_SubLinkType_index)-1) {
		return "SubLinkType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SubLinkType_name[_SubLinkType_index[i]:_SubLinkType_index[i+1]]
}
